### ISSUE TITLE
API auth Pinboard.in?

### ISSUE THREAD

**Issue by flips** [canisbos/Cloudmarks#2]
How can I tell/setup the API token in Cloudmarks?
The FAQ states that I `should see an item named “api.pinboard.in” followed by your username in parentheses. Double-click this item.`
But I don't see that. Maybe the extension is not updates to handle current API?
(Most pinboard extensions for other browsers require API key in settings, in the format of user:LONGSTRING)

**Comment by canisbos** [comment]
Cloudmarks does not use a token for authentication. It uses basic authentication, which sends your username and password (securely). That's why it depends on your password for api.pinboard.in being stored in your login keychain.

However, I think Apple's recent integration of the keychain with iCloud has done something that interferes with Cloudmarks. Here is a workaround:

1. Open a new tab in Safari and go to this URL: https://api.pinboard.in/v1/posts/update

2. If a dialog box pops up prompting you to enter your username and password, do so, and be sure to check the box to remember the password. Now you should be able to use Cloudmarks.

If no prompt appears, let me know what you see in the tab.

**Comment by flips** [comment]
Yep, that works, thanks 👍 😄 Looks good. I kinda wish I could organize my pinboard bookmarks from the same interface 😃

**Comment by canisbos** [comment]
Yes, that would be nice, but I stopped adding new features to these extensions a long time ago. My job intervened. ;)
